# 选择基础镜像
FROM openjdk:8u342-jdk

# 设置环境变量
ENV JAVA_HOME="/usr/local/openjdk-8/" 
ENV PATH="/opt/apache-doris/be/bin:$PATH"

# 下载软件至镜像内，可根据需要替换
ADD ./resource/apache-doris/ /opt/

RUN apt-get update && \
    apt-get install -y default-mysql-client && \
    apt-get clean && \
    mkdir /opt/apache-doris && \
    cd /opt && \
    mv apache-doris/be /opt/apache-doris/

ADD ./be/resource/init_be.sh /opt/apache-doris/be/bin
ADD ./be/resource/start_be.sh /opt/apache-doris/be/bin
RUN chmod 755 /opt/apache-doris/be/bin/init_be.sh
RUN chmod 755 /opt/apache-doris/be/bin/start_be.sh

ENTRYPOINT ["/opt/apache-doris/be/bin/init_be.sh"]